spring.application.name=sipvs-mladost
protokol.xsd=schema/protokol.xsd
protokol.xsl=schema/protokol.xsl
protokol.xml=data/protokol.xml
protokol.html=data/protokol.html
protokol.pdf=data/protokol.pdf
protokol.asice=data/protokol.asice
